### ISSUE TITLE
SQLAlchemy Interface Error

### ISSUE THREAD

**Issue by kylejb** [clairBuoyant/server#46]
`GET api/v1/buoys`: [InterfaceError](https://sqlalche.me/e/14/rvf5) was raised. Since we're using `asyncpg` with SQLAlchemy, we should make sure we're managing our connections correctly. See log below for more details.

_FYI - this log was raised after querying buoys data to populate [WorldMap component in our UI](https://github.com/clairBuoyant/web/blob/main/src/routes/routes.tsx#L22)._ 

```
INFO:     127.0.0.1:63855 - "GET /api/v1/buoys/ HTTP/1.1" 200 OK
2022-09-30 09:17:01,910 INFO sqlalchemy.engine.Engine ROLLBACK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 729, in rollback
    self.await_(self._transaction.rollback())
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/asyncpg/transaction.py", line 219, in rollback
    await self.__rollback()
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/asyncpg/transaction.py", line 198, in __rollback
    await self._connection.execute(query)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/asyncpg/connection.py", line 318, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 323, in query
  File "asyncpg/protocol/protocol.pyx", line 707, in asyncpg.protocol.protocol.BaseProtocol._check_state
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1057, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 682, in do_rollback
    dbapi_connection.rollback()
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 731, in rollback
    self._handle_exception(error)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.InterfaceError: <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 15, in __call__
    async with AsyncExitStack() as stack:
  File "/Users/kylejb/.asdf/installs/python/3.10.7/lib/python3.10/contextlib.py", line 714, in __aexit__
    raise exc_details[1]
  File "/Users/kylejb/.asdf/installs/python/3.10.7/lib/python3.10/contextlib.py", line 697, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/Users/kylejb/.asdf/installs/python/3.10.7/lib/python3.10/contextlib.py", line 206, in __aexit__
    await anext(self.gen)
  File "$HOME/clairBuoyant/server/server/api/dependencies.py", line 12, in get_db
    await db.close()
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 613, in close
    await greenlet_spawn(self.sync_session.close)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 126, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1809, in close
    self._close_impl(invalidate=False)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1851, in _close_impl
    transaction.close(invalidate)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 923, in close
    transaction.close()
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2416, in close
    self._do_close()
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2639, in _do_close
    self._close_impl()
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2625, in _close_impl
    self._connection_rollback_impl()
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2617, in _connection_rollback_impl
    self.connection._rollback_impl()
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1059, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1057, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 682, in do_rollback
    dbapi_connection.rollback()
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 731, in rollback
    self._handle_exception(error)
  File "$HOME/clairBuoyant/server/.venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.InterfaceError: (sqlalchemy.dialects.postgresql.asyncpg.InterfaceError) <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress
(Background on this error at: https://sqlalche.me/e/14/rvf5)
The garbage collector is trying to clean up connection <AdaptedConnection <asyncpg.connection.Connection object at 0x103548660>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
sys:1: SAWarning: The garbage collector is trying to clean up connection <AdaptedConnection <asyncpg.connection.Connection object at 0x103548660>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
The garbage collector is trying to clean up connection <AdaptedConnection <asyncpg.connection.Connection object at 0x103548ac0>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
$HOME/clairBuoyant/server/server/api/v1/endpoints/buoys.py:16: SAWarning: The garbage collector is trying to clean up connection <AdaptedConnection <asyncpg.connection.Connection object at 0x103548ac0>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
  return await buoy.find_many(db_session=db_session)
INFO:     127.0.0.1:63857 - "GET /api/v1/buoys/ HTTP/1.1" 200 OK
```

**Comment by kylejb** [comment]
Closed by https://github.com/clairBuoyant/server/pull/47 and https://github.com/clairBuoyant/server/pull/48.
